### ISSUE TITLE
Wi-fi instável BTVE10

### ISSUE THREAD

**Issue by Piadista** [educabox/educabox#1]
Imagem live otimizada Armbian educabox_armbian_btve10_live.img.gz não permite uma conexão estável com uma rede wi-fi.

**Comment by educabox** [comment]
Bom dia Piadista!

Com relação ao wifi da BTVE10 em nossa bancada utilizamos sem problema algum, porém como essas TVs Boxes são chinesas há uma variação enorme de chips, capacitores e outros itens eletrônicos em um mesmo modelo, então é necessário investigar se a sua BTVE10 está utilizando a mesma placa que usamos aqui (RTL8189FTV) em caso afirmativo e mesmo assim o problema persistir recomendo seguir o tutorial abaixo:

Link: [Instruction on how to use wireless WoL (Wake on LAN) using RTL8189FS (RTL8189FTV) module](https://forum.armbian.com/topic/33452-instruction-on-how-to-use-wireless-wol-wake-on-lan-using-rtl8189fs-rtl8189ftv-module/?_mfaLogin=1)

Aqui nós nunca testamos, mas caso vocês consigam é um ponto de partida para outros projetos que tenham o mesmo problema.
Se solucionarem o problema, aguardamos um feedback de vocês!

Atenciosamente.
